import React from 'react';
import CopyButton from './CopyButton';
import { createLineDecorationTransformer, highlightToHtml } from './shiki';

interface LineAnnotation {
  lineNumber: number;
  note: string;
}

interface AnnotatedCodeProps {
  code: string;
  language?: string;
  showLineNumbers?: boolean;
  annotations?: LineAnnotation[];
  highlightLines?: number[];
  className?: string;
}

/**
 * AnnotatedCode: Server Component extending CodeBlock with per-line
 * annotations. Highlighting comes from the same Shiki singleton as
 * CodeBlock (see shiki.ts); highlighted lines (2px left bar + subtle
 * background) and annotation markers (real, visible note text) are layered
 * on top of the highlighted tokens via a Shiki transformer that adds line
 * classes and appends a note element to the HAST tree — not by re-rendering
 * the code as plain text.
 */
export async function AnnotatedCode({
  code,
  language = 'text',
  showLineNumbers = true,
  annotations = [],
  highlightLines = [],
  className = '',
}: AnnotatedCodeProps) {
  const cleanCode = code.trimEnd();

  const annotationMap = new Map(annotations.map((ann) => [ann.lineNumber, ann.note]));
  const highlightSet = new Set(highlightLines);

  const { html } = await highlightToHtml(cleanCode, language, {
    showLineNumbers,
    transformers: [
      createLineDecorationTransformer({
        highlightLines: highlightSet,
        annotations: annotationMap,
      }),
    ],
  });

  return (
    <div
      className={`rounded-lg overflow-hidden border border-line-hairline bg-surface-raised ${className}`}
    >
      {/* Language chip */}
      {language && language !== 'text' && (
        <div className="px-4 py-2 bg-surface-overlay border-b border-line-hairline text-ink-muted text-label font-mono flex justify-between items-center">
          <span>{language}</span>
        </div>
      )}

      {/* Code container — HTML generated by Shiki on the server, decorated
          with highlight/annotation line classes by createLineDecorationTransformer */}
      <div className="relative group">
        <div
          className="shiki-container p-4 overflow-x-auto font-mono text-body leading-relaxed"
          aria-label={`Code block in ${language}`}
          dangerouslySetInnerHTML={{ __html: html }}
        />

        {/* Copy button */}
        <CopyButton code={cleanCode} />
      </div>

      {/* Annotations legend — plain, always-visible text for every note,
          independent of the inline markers above */}
      {annotations.length > 0 && (
        <div className="px-4 py-3 bg-surface-overlay border-t border-line-hairline">
          <div className="text-label font-semibold text-ink-secondary mb-2">
            Annotations
          </div>
          <ul className="space-y-1 text-body">
            {annotations.map((ann) => (
              <li key={ann.lineNumber} className="flex gap-2 text-ink-secondary">
                <span className="w-6 h-6 rounded-full bg-brand text-white text-xs font-bold flex items-center justify-center flex-shrink-0">
                  ●
                </span>
                <span>
                  <strong>Line {ann.lineNumber}:</strong> {ann.note}
                </span>
              </li>
            ))}
          </ul>
        </div>
      )}
    </div>
  );
}

