import React from 'react';
import CopyButton from './CopyButton';
import { highlightToHtml } from './shiki';

interface CodeBlockProps {
  code: string;
  language?: string;
  showLineNumbers?: boolean;
  className?: string;
}

/**
 * CodeBlock: Server Component that highlights code with Shiki, on the server,
 * using a single cached highlighter (see shiki.ts). The highlighter itself
 * never reaches the client — only the resulting HTML (tokens colored via
 * `--shiki-light` / `--shiki-dark` CSS variables) is sent down. The copy
 * button is the only client-side JS in this tree.
 */
export async function CodeBlock({
  code,
  language = 'text',
  showLineNumbers = false,
  className = '',
}: CodeBlockProps) {
  const cleanCode = code.trimEnd();
  const { html } = await highlightToHtml(cleanCode, language, { showLineNumbers });

  return (
    <div
      className={`rounded-lg overflow-hidden border border-line-hairline bg-surface-raised ${className}`}
    >
      {/* Language chip */}
      {language && language !== 'text' && (
        <div className="px-4 py-2 bg-surface-overlay border-b border-line-hairline text-ink-muted text-label font-mono flex justify-between items-center">
          <span>{language}</span>
        </div>
      )}

      {/* Code container — HTML generated by Shiki on the server */}
      <div className="relative group">
        <div
          className="shiki-container p-4 overflow-x-auto font-mono text-body leading-relaxed"
          dangerouslySetInnerHTML={{ __html: html }}
        />

        {/* Copy button */}
        <CopyButton code={cleanCode} />
      </div>
    </div>
  );
}

export default CodeBlock;
