import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by dms-engine v3 and copied in by scripts/sync-engine-v3.js (git-ignored):
    "data/engine/**",
    "server-data/engine/**",
    // Playwright output:
    "playwright-report/**",
    "test-results/**",
  ]),
  {
    // package.json has no "type": "module", and this file is invoked directly
    // as `node scripts/sync-engine-v3.js` from prebuild.sh, dev-engine.sh and
    // the CI workflows, so it must stay CommonJS — `require` here isn't a
    // mistake.
    files: ["scripts/sync-engine-v3.js"],
    rules: {
      "@typescript-eslint/no-require-imports": "off",
    },
  },
]);

export default eslintConfig;
