#!/usr/bin/env node

/**
 * check-no-hex.mjs — guardrail for the design-token system (DS2).
 *
 * Fails if any hex color literal (#fff, #ffffff, #ffffffff, ...) appears in
 * app/**\/*.{ts,tsx,css}, outside of:
 *   - app/globals.css                      (the token file itself)
 *   - app/(components)/diagram-assets/**    (generated by dms-engine)
 *   - app/solutions/**                      (generated by dms-engine)
 *
 * All other colors must be design tokens (CSS variables / Tailwind theme
 * utilities defined in app/globals.css), not literal hex values.
 *
 * Usage: node scripts/check-no-hex.mjs   (npm run lint:colors)
 */

import { readdirSync, readFileSync, statSync } from 'node:fs';
import { join, relative, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = fileURLToPath(new URL('.', import.meta.url));
const ROOT = join(__dirname, '..');
const APP_DIR = join(ROOT, 'app');

const SCAN_EXTENSIONS = new Set(['.ts', '.tsx', '.css']);

// Paths (relative to app/) that are exempt from this check.
const EXEMPT_PREFIXES = [
  join('(components)', 'diagram-assets') + sep,
  'solutions' + sep,
];
const EXEMPT_FILES = new Set(['globals.css']);

// Matches #abc, #abcd, #aabbcc, #aabbccdd — word-bounded so it doesn't fire
// on longer alphanumeric runs, and not immediately after `href=` (page
// anchors like href="#top" are not colors).
const HEX_COLOR_RE = /#(?:[0-9a-fA-F]{8}|[0-9a-fA-F]{6}|[0-9a-fA-F]{4}|[0-9a-fA-F]{3})\b/g;
const HREF_ANCHOR_RE = /href\s*=\s*["'][^"']*$/i;

function isExempt(relPath) {
  if (EXEMPT_FILES.has(relPath)) return true;
  return EXEMPT_PREFIXES.some((prefix) => relPath.startsWith(prefix));
}

function walk(dir, files = []) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      if (entry === 'node_modules' || entry === '.next') continue;
      walk(full, files);
    } else if (SCAN_EXTENSIONS.has(entry.slice(entry.lastIndexOf('.')))) {
      files.push(full);
    }
  }
  return files;
}

function findViolations(filePath) {
  const content = readFileSync(filePath, 'utf-8');
  const lines = content.split('\n');
  const violations = [];

  lines.forEach((line, idx) => {
    HEX_COLOR_RE.lastIndex = 0;
    let match;
    while ((match = HEX_COLOR_RE.exec(line))) {
      const before = line.slice(0, match.index);
      if (HREF_ANCHOR_RE.test(before)) continue; // e.g. href="#top"
      violations.push({ line: idx + 1, column: match.index + 1, text: match[0], source: line.trim() });
    }
  });

  return violations;
}

function main() {
  const files = walk(APP_DIR);
  const allViolations = [];

  for (const file of files) {
    const relPath = relative(APP_DIR, file);
    if (isExempt(relPath)) continue;
    const violations = findViolations(file);
    if (violations.length > 0) {
      allViolations.push({ relPath, violations });
    }
  }

  if (allViolations.length === 0) {
    console.log('✓ lint:colors — no hex color literals found outside app/globals.css');
    process.exit(0);
  }

  console.error('✗ lint:colors — hex color literals found outside app/globals.css:\n');
  for (const { relPath, violations } of allViolations) {
    for (const v of violations) {
      console.error(`  app/${relPath}:${v.line}:${v.column}  ${v.text}   ${v.source}`);
    }
  }
  console.error(
    `\n${allViolations.reduce((n, f) => n + f.violations.length, 0)} violation(s) in ${allViolations.length} file(s).`
  );
  console.error('Replace hex literals with a design token from app/globals.css (see the design spec).');
  process.exit(1);
}

main();
